#!/bin/bash
random_char ()
{
  cat /dev/urandom| tr -dc '0-9a-zA-Z'| head -c $1
}

ord() {
  LC_CTYPE=C printf '%d' "'$1"
}

chr() {
  [ "$1" -lt 256 ] || return 1
  printf "\\$(printf '%03o' "$1")"
}

SRC=$(random_char 100)
TOTAL=0
STRING=""

while [ $TOTAL -lt 3566 ]
do
  C=$(echo $SRC | head -c 1)
  SRC=${SRC:1}
  V=$(ord $C)
  R=$((3566 - $TOTAL))
  if [ $V -gt $R ]; then
    V=$R
    C=$(chr $R)
  fi
  TOTAL=$[$TOTAL + $V]
  STRING="$STRING$C"
done

echo $STRING
